server:
  port: 80

spring:
  datasource:
    druid:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cs307_pro2
    username: agou
    password: agou123


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl